locale: "en-US"
title: Open Source Security Software Hackathon 2017 # Title of your site
url: "https://hackathon.hack.lu" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
    The Open Source Security Software Hackathon is a 2-days open hackathon to bring
    people and open source security software/tools together.
# Author details for the jekyll-seo-tag gem
author:
  name: hack.lu team
  email: info@hack.lu
  twitter: hack_lu # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Open Source Security Software Hackathon 2017
  links:
    - https://hackathon.hack.lu

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
